sudo: false
language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- export SHELLWHAT_PARSER='docker'
- make test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: cLGsJOcHA9QSH88XYMqZaxN67VXNHlpsGL2xzXlffmj6iZWus0LzMqa/Tsijme9SsyiEO3PL+RVBbwi3O0eE1QXyT2bqH3/M0cWM8iZ0lxssFSQyri/iPhk41zuu7f6mW7oRDsst7uWyTJwdwSxcUr/P3YVD/g4Sh6rtH38y7oW/cOFwOH77J/geWYoPsR50iKlggqWDIqpNtnxqLSvoh3DQxNZGbsmnyci5b1evLzUqFCNyn68E+0ltobPaxHXxcRFR++epGMH+WKyYUyWiRGfNMim6cmc6WIntRsSJttYtmONxFd1PmP6+JPFvOBNO+DRMm0w+5fT1TdpMLT+A9FKyyVU52Mj+PGu0rgdvy91fNNVT3Qx72ClmV6yaMkd8LkJBk1xBPOFznq/J5sBi00IxGiHoMP0WVoGpMosj5wz+Gc2JdVf2yPzGLK+A4KddF74zCERb7aLhnIDZOYDQA8iSUui0RLHs81DK5NlrPqvkr/xKxpMW1DYgfm/JtcUeMZzhN5lWeFksYZSTFDCrCivZ7uFduxURLTinUmxdAstmxH/92xiwpdM4adD+kU5j4t+q+BaYyk/XkUIlk8EMxb+6pCnPmDt+Ys+E9+JWWOBi93XFCqUkYW0EouvkfTiYT8FRd3CPS3gZr9Lu4eMj6LRjRhMvtXhG0s3LwoG0zlQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/shellwhat
    skip_upload_docs: true
